### ISSUE TITLE
Add the possibility to disable device removal

### ISSUE THREAD

**Issue by guydunigo** [michelesr/nvidia-xrun-pm#5]
Hi, on my laptop, when the device is removed and re-added via the 'rescan', it won't work again
('modprobe nvidia' says device not found).
However, simply setting the pci device power/control  to auto works to stop the card.
 
It would be good to add the possibility to disable the removal via some env variable and reenable the auto power when starting the nvidia-xrun.
A possible solution would be:
```
  if [[ ${DONT_REMOVE_DEVICE} -eq 1 ]]
    then
    echo "Setting Nvidia bus power control to auto"
    execute "sudo tee /sys/bus/pci/devices/${DEVICE_BUS_ID}/power/control <<<auto"
  else
    echo 'Removing Nvidia bus from the kernel'
    execute "sudo tee /sys/bus/pci/devices/${DEVICE_BUS_ID}/remove <<<1"
fi
```

(Btw: Have you tried my solution on your computer ? Maybe it would do the trick for you as well)

**Comment by michelesr** [comment]
I'm aware that setting the device power control to `auto` will cause the device to turn off. However, the reason nvidia-xrun-pm is removing the device is to make it invisible to the system so that the `nvidia` module can't be loaded automatically (causing the graphic card to be turned on again). There are different situation where the `nvidia` module gets loaded automatically:

- Xorg loads the nvidia module automatically at start when using the `modesetting` driver, because that driver is generic and designed to work with KMS (Kernel Mode Setting) so it will attempt to load any available kernel module that provides KMS for the existing devices (and so `nvidia`)

- If Xorg is set to use the `intel` driver instead, some DE will still load the nvidia module, for example GNOME shell

Because of this, simply putting the power control to auto isn't enough to guarantee that the card won't turn on again.

We could add the flag, but it should default to the removal behavior, to cover also those users using GNOME or the modesetting X driver (which seems to be recommended choice for newer Intel graphic cards).

Recently nvidia-xrun-pm code has been merged into nvidia-xrun pm again, so the plan is to archive this project and support the original codebase, so I'm not very keen to diverge from upstream again.

Now, I struggled in the past to understand why the graphic card doesn't get added back during a `rescan` operation, and I found that (at least in my laptop) if the power state for the PCI express controller that hosts the graphic card is set to `auto`, the card won't be detected during the `rescan`. The script should take care of setting the controller power control to `on` automatically before attempting rescan, but it might fail due to the following reasons:

- `CONTROLLER_BUS_ID` is pointing to the wrong id in `/etc/default/nvidia-xrun`
- another power saving software like powertop or TLP is forcing the controller power control to `auto`

@guydunigo can you please check that `CONTROLLER_BUS_ID` is set to the right value? It should point to the id of the PCI express controller hosting the card (you can find the id by inspecting the output of `lshw`).

**Comment by guydunigo** [comment]
@michelsr
When rescanning, the PCI device reappears and CONTROLLER_BUS_ID is well recognized, but the problem is that the nvidia module can't load because it says it can't find the card.
Maybe you know a way to specify directly to the nvidia module the pci infos of the card and to force it to load ?

I got a probably similar problem with bbswitch, it could turn off the card but not back on...

**Comment by michelesr** [comment]
Sorry, I misunderstood the problem. Can you try to manually run the commands in the script and see if you get any error (and also check the log in dmesg)? You can print the commands using `nvidia-xrun -d`

In particular I'm interested in knowing if the modules can get properly unloaded before running the remove command and whether there are other problems that could get reported in dmesg. 

In my system after the rescan you can simply modprobe the module without problems.

**Comment by michelesr** [comment]
@guydunigo I'm transferring the issue upstream as I don't want to diverge again and if we're going to implement the flag it would be better to be in the upstream project.
